### PR TITLE
Bug Fix and NPRML Construction Fixes

### PR DESCRIPTION
**Pull request by jwcounts**
The bug fix is in ds-npr-api.php and only affects situations in which the plugin is being activated in a multisite setup.

The NPRML fixes removes the previous version's reliance on the guid as a stand-in for the URL of attachments. If you use a plugin to offload your media files to a CDN, any article you push to the API will have broken images.

Also allows for having multiple audio files attached, and not relying on the <enclosure> tags generated by Wordpress, as they can be unreliable sometimes.

### CODE REVIEW

**Comment by tamw-wnet** [comment]
@jwcounts there's some merge conflicts that I think you're best to resolve here.

**Comment by jwcounts** [comment]
Yes, I did see that. Thank you for handling them.

**Comment by jwcounts** [comment]
Went in a cleaned up the bugs I introduced, and merged and cleaned up the changes from the main branch. Also made a tweak to the image attachment handling in NPRAPIWordpress.php, since the attachment GUID is not always a reliable proxy for the attachment URL.

Give it a look, let me know if you run into any bugs, and then I can work on resolving the merge conflicts.

**Comment by tamw-wnet** [comment]
@jwcounts There's a ton of conflicts that need to be merged still, and since none of the new functionality I've been using is in I can't really review this very well in my working environment.   I _really_ think it would be better to back out the styling changes, merge in the pending stuff you had before then, lets review that, and then do the styling changes.   It'll make the whole process much more doable for reviewing and testing.   

Otherwise, if you want to go through and do all the merges first, go for it.

**Comment by tamw-wnet** [comment]
PS @jwcounts sorry if I'm sounding unhelpful -- there's just not much I can do to test this, it's reviewing a styling rewrite of an older version of the software than what I depend on.    If you go ahead and handle the merge conflicts I can review that.

**Comment by jwcounts** [comment]
It’s actually not that different at the moment. I spent a lot of time before my last commit merging in all of the changes from main and testing them, so most of the conflicts are down to styling in those 5 files. I got sidetracked by another project and will work through those later today.

Jared Counts

**Comment by tamw-wnet** [comment]
@jwcounts I've got this in my dev environment now and am doing a lot of testing, I've found no issues thus far.   I don't push stories to the API however, so it would be great if someone can test that.

**Comment by jwcounts** [comment]
Yeah, I'll do some testing on my end. I tried pushing to the sandbox from my dev server but I got an "IP address not authenticated" error (which is odd because sandbox?).

**Comment by jwcounts** [comment]
Was able to use a proxy and test pushing an article into the API. I was able to successfully upload a story into the API, but deleting the story locally didn't delete in the Story API. Going to take a closer look at that.

**Comment by jwcounts** [comment]
Found some errors in nprstory_api_delete() in push_story.php. It was doing some unnecessary checks, and some of the logic seemed to be pulled from nprstory_api_push(). Successfully tested creating a post, pushing it to the API, deleting it locally, and pushing the delete action to the API as well.

**Pull request merged**
