### PR TITLE
Generate WP posts with rich layout including multimedia etc

### PR DESCRIPTION
**Pull request by tamw-wnet**
The NPR Story API includes a 'layout' section for most stories that references inline the placement of multimedia objects such as images, videos, Twitter embeds, javascript widgets, etc.   This pull request adds the ability for the WP site admin to import stories using that rich layout including the multimedia objects, in the order they appeared in the NPR.org story.   It adds a checkbox to the admin to enable this functionality.    As of this commit, Slideshows are not imported, only the first image in the slideshow.

### CODE REVIEW

**Review by jwcounts — APPROVED** [review]
Code looks good, and I like that the additions are only enabled if the "layout" tag is included in the API response. I would really like to test it with data from the API, but I haven't been able to find an article with the "layout" tag available yet.

**Comment by tamw-wnet** [comment]
@jwcounts I think you actually have to make a request to NPR to have the 'layout' stuff added to your key.

**Comment by jwcounts** [comment]
Okay, waiting to hear back from NPR Support. I'm good with merging in the meantime.

**Comment by tamw-wnet** [comment]
I'm going to add some help text to the README and/or the settings page so people know how to enable 'layout' for their keys.  "They should open a ticket requesting layout permissions for their Story API Key. Have them please provide the key in the request so we can make sure we know which one we're adding those permissions to."

**Comment by jwcounts** [comment]
Sounds good

Jared Counts

**Comment by tamw-wnet** [comment]
@jwcounts I've added the help text -- I'm going to let you make that request to NPR so you can see what the behavior is with the layout stuff before pushing this forward.

**Review by jwcounts — COMMENTED** [review]
I would suggest breaking the added line into it's own paragraph, maybe bolded or italicized. You would end up with 3 paragraphs, which may make it a little more legible.

**Review by jwcounts — APPROVED** [review]
That works

**Pull request merged**
